repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      args: ['--line-length=88', '--preview']
      language: python
      types: [python]
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      args: ['--max-line-length=88', '--ignore=E203,W503,E231,E266,E722']
      language: python
      types: [python]